version: "3"
services: 
  hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    restart: always 
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    restart: on-failure:3
  firefox:
    image: selenium/node-firefox:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    shm_size: '1gb'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    restart: on-failure:3